[project]

# Information
site_name = "中文 Duckling"
site_description = "中文 Duckling | Duckling Chinese"
site_author = "范叶亮 | Leo Van"
site_url = "https://duckling.leovan.tech"
copyright = """
版权所有 &copy; 2023-2026，<a href="https://leovan.me" target="_blank">范叶亮 | Leo Van</a>
"""

# Repository
repo_name = "leovan/duckling-chinese"
repo_url = "https://github.com/leovan/duckling-chinese"

# Javascript
extra_javascript = [
  "javascripts/mathjax.js",
  "https://cdn.jsdmirror.com/npm/mathjax@4/tex-chtml.js",
  "https://cdn.jsdmirror.com/npm/tablesort@5.7.0/dist/tablesort.min.js",
  "javascripts/tablesort.js",
]

# Style
extra_css = [
  "stylesheets/extra.css",
]

# Navigation
nav = [
  { "主页" = "index.md" },
  { "接口" = "api.md" },
  { "维度" = [
    "dimension/index.md",
    "dimension/act.md",
    "dimension/age.md",
    "dimension/area.md",
    "dimension/blood-type.md",
    "dimension/constellation.md",
    "dimension/currency.md",
    "dimension/date.md",
    "dimension/digit-sequence.md",
    "dimension/distance.md",
    "dimension/duplicate.md",
    "dimension/duration.md",
    "dimension/episode.md",
    "dimension/fraction.md",
    "dimension/gender.md",
    "dimension/level.md",
    "dimension/lyric.md",
    "dimension/multi-char.md",
    "dimension/multiple.md",
    "dimension/numeral.md",
    "dimension/ordinal.md",
    "dimension/phone-number.md",
    "dimension/place.md",
    "dimension/quantity.md",
    "dimension/rating.md",
    "dimension/repeat.md",
    "dimension/season.md",
    "dimension/temperature.md",
    "dimension/time.md",
    "dimension/url.md",
    "dimension/velocity.md",
  ] },
  { "排序" = [
    "ranker/index.md",
    "ranker/naive-bayes.md",
  ] },
]

# Theme
[project.theme]

favicon = "images/logo.png"
logo = "images/logo.png"

language = "zh"

features = [
  "announce.dismiss",
  "content.code.annotate",
  "content.code.copy",
  "content.code.select",
  "content.footnote.tooltips",
  "content.tabs.link",
  "content.tooltips",
  "navigation.footer",
  "navigation.indexes",
  "navigation.instant",
  "navigation.instant.prefetch",
  "navigation.path",
  "navigation.sections",
  "navigation.tabs",
  "navigation.tabs.sticky",
  "navigation.top",
  "navigation.tracking",
  "toc.follow",
  "search.highlight",
]

[[project.theme.palette]]
scheme = "default"
primary = "amber"
accent = "amber"
toggle.icon = "lucide/sun"
toggle.name = "切换至暗黑模式"

[[project.theme.palette]]
scheme = "slate"
primary = "amber"
accent = "amber"
toggle.icon = "lucide/moon"
toggle.name = "切换至亮色模式"

[project.theme.icon]
repo = "fontawesome/brands/git-alt"

# Extra
[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/leovan"

[[project.extra.social]]
icon = "fontawesome/solid/house"
link = "https://leovan.me"

[project.extra.analytics]
provider = "google"
property = "G-RS00KBSHXE"

# Extensions
[project.markdown_extensions.abbr]
[project.markdown_extensions.admonition]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.def_list]
[project.markdown_extensions.footnotes]
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.tables]

[project.markdown_extensions.toc]
permalink =  true
toc_depth = 3

[project.markdown_extensions.toc.slugify]
object = "pymdownx.slugs.slugify"
kwds = { case = "lower" }

[project.markdown_extensions.pymdownx.arithmatex]
generic = true

[project.markdown_extensions.pymdownx.blocks.caption]
[project.markdown_extensions.pymdownx.caret]
[project.markdown_extensions.pymdownx.details]

[project.markdown_extensions.pymdownx.emoji]
emoji_index = "zensical.extensions.emoji.twemoji" 
emoji_generator = "zensical.extensions.emoji.to_svg"

[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true

[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.keys]
[project.markdown_extensions.pymdownx.mark]
[project.markdown_extensions.pymdownx.progressbar]
[project.markdown_extensions.pymdownx.snippets]

[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" }
]

[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
combine_header_slug = true

[project.markdown_extensions.pymdownx.tabbed.slugify]
object = "pymdownx.slugs.slugify"
kwds = { case = "lower" }

[project.markdown_extensions.pymdownx.tasklist]
custom_checkbox = true

[project.markdown_extensions.pymdownx.tilde]
